steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '--tag', 'gcr.io/$PROJECT_ID/postgres', '--tag', 'gcr.io/$PROJECT_ID/postgres:9.3', '.']

images: ['gcr.io/$PROJECT_ID/postgres']
